package com.motobe.expensetracker;

public enum SpendCategory {
    POCKET_SELF,
    TRANSPORT_SELF,
    FEEDING_SELF,
    CLOTHING_SELF,
    BUY_THINGS_SELF,
    DO_PROJECT_SELF,
    EDUCATION_SELF,
    ENTERTAINMENT_SELF,
    INVESTMENT_SELF,
    ASSIST_FAMILY,
    LEND_FAMILY,
    ASSIST_FRIEND,
    LEND_FRIEND,
    HELP_STRANGER,
    REPAY_LOAN;
}
